import React, { useState } from 'react';
import {
  Lock,
  Eye,
  MessageSquare,
  TrendingUp,
  DollarSign,
  Radio,
  CheckCircle,
  AlertTriangle,
  ArrowRight,
  ShieldAlert,
} from 'lucide-react';
import type { MetricsFrameworkItem } from '../../lib/types';

interface MetricsFrameworkProps {
  metrics: MetricsFrameworkItem[];
}

// Fallback static metrics framework items matching the database seed
const DEFAULT_METRICS: MetricsFrameworkItem[] = [
  { id: 1, category: 'Attention', metric_name: 'Hook Rate', description: '% of users who keep watching/reading past the first 3 seconds or opening line', requires_api: true },
  { id: 2, category: 'Attention', metric_name: '3s/5s Video View Rate', description: '% of total impressions that watched at least 3s or 5s of the video creative', requires_api: true },
  { id: 3, category: 'Attention', metric_name: 'Click-Through Rate (CTR)', description: 'Clicks divided by impressions (outbound clicks to app store landing page)', requires_api: true },
  { id: 4, category: 'Engagement', metric_name: 'Engagement Rate', description: 'Sum of reactions, comments, and shares divided by total impressions', requires_api: true },
  { id: 5, category: 'Engagement', metric_name: 'Video Watch Time', description: 'Average continuous seconds watched per user playback', requires_api: true },
  { id: 6, category: 'Engagement', metric_name: 'Video Completion Rate', description: '% of viewers who watched the full video creative to the end', requires_api: true },
  { id: 7, category: 'Engagement', metric_name: 'Shares', description: 'Total number of organic shares generated by the ad creative', requires_api: true },
  { id: 8, category: 'Engagement', metric_name: 'Saves', description: 'Total number of bookmarks/saves on the ad post', requires_api: true },
  { id: 9, category: 'Engagement', metric_name: 'Comments', description: 'Total public comment count reflecting audience discussion and sentiment', requires_api: true },
  { id: 10, category: 'Conversion', metric_name: 'Conversion Rate', description: '% of landing page or ad clicks that result in an app install', requires_api: true },
  { id: 11, category: 'Conversion', metric_name: 'Install-to-Trial Rate', description: '% of app installers who initiate the ₹1 trial or free onboarding lesson', requires_api: true },
  { id: 12, category: 'Conversion', metric_name: 'Lead Conversion Rate', description: '% of users submitting contact details or completing registration', requires_api: true },
  { id: 13, category: 'Conversion', metric_name: 'Purchase Rate', description: '% of trial users converting into paid recurring English learning subscribers', requires_api: true },
  { id: 14, category: 'Cost & ROI', metric_name: 'Cost Per Mille (CPM)', description: 'Cost per 1,000 ad impressions delivered in target geography', requires_api: true },
  { id: 15, category: 'Cost & ROI', metric_name: 'Cost Per Click (CPC)', description: 'Average spend per outbound click to the MySivi app store page', requires_api: true },
  { id: 16, category: 'Cost & ROI', metric_name: 'Cost Per Lead (CPL)', description: 'Average cost incurred to acquire an email or phone registration', requires_api: true },
  { id: 17, category: 'Cost & ROI', metric_name: 'Cost Per Acquisition (CPA)', description: 'Blended cost to acquire one validated new app trial user', requires_api: true },
  { id: 18, category: 'Cost & ROI', metric_name: 'Return on Ad Spend (ROAS)', description: 'Gross revenue generated divided by ad spend (key scaling compass)', requires_api: true },
  { id: 19, category: 'Reach & Delivery', metric_name: 'Reach', description: 'Unique individuals who saw the ad creative at least once', requires_api: true },
  { id: 20, category: 'Reach & Delivery', metric_name: 'Impressions', description: 'Total number of times the ad was displayed on screen', requires_api: true },
  { id: 21, category: 'Reach & Delivery', metric_name: 'Frequency', description: 'Average number of times each unique person was shown the ad', requires_api: true }
];

export const MetricsFramework: React.FC<MetricsFrameworkProps> = ({ metrics }) => {
  const items = metrics && metrics.length > 0 ? metrics : DEFAULT_METRICS;
  const [selectedCategory, setSelectedCategory] = useState<string>('All');

  const categories = ['All', 'Attention', 'Engagement', 'Conversion', 'Cost & ROI', 'Reach & Delivery'];

  const filteredItems = selectedCategory === 'All'
    ? items
    : items.filter((m) => m.category === selectedCategory);

  const getCategoryIcon = (cat: string) => {
    switch (cat) {
      case 'Attention':
        return <Eye className="w-4 h-4 text-sky-500" />;
      case 'Engagement':
        return <MessageSquare className="w-4 h-4 text-indigo-500" />;
      case 'Conversion':
        return <TrendingUp className="w-4 h-4 text-emerald-500" />;
      case 'Cost & ROI':
        return <DollarSign className="w-4 h-4 text-amber-500" />;
      case 'Reach & Delivery':
        return <Radio className="w-4 h-4 text-purple-500" />;
      default:
        return <TrendingUp className="w-4 h-4 text-slate-500" />;
    }
  };

  return (
    <div className="space-y-8">
      {/* Reality Check Callout Box */}
      <div className="bg-gradient-to-r from-slate-900 to-indigo-950 text-white rounded-3xl p-6 sm:p-8 shadow-xl relative overflow-hidden">
        <div className="relative z-10 space-y-4">
          <div className="inline-flex items-center gap-2 bg-amber-400 text-amber-950 px-3 py-1 rounded-full text-xs font-extrabold">
            <Lock className="w-3.5 h-3.5" />
            Meta Marketing API Roadmap
          </div>

          <h2 className="text-2xl sm:text-3xl font-extrabold tracking-tight">
            Comprehensive Growth Metrics Framework
          </h2>

          <p className="text-sm text-slate-300 max-w-3xl leading-relaxed">
            Meta strictly withholds private commercial metrics (spend, impressions, CTR, conversion rates, and ROAS) from the public Facebook Ad Library. These 20 KPIs represent our production measurement architecture, designed to connect directly into MySivi's authenticated Meta Ads Manager Marketing API.
          </p>

          <div className="pt-2 flex flex-wrap gap-4 text-xs font-medium text-slate-300">
            <div className="flex items-center gap-2 bg-white/10 px-3 py-1.5 rounded-xl border border-white/10">
              <CheckCircle className="w-4 h-4 text-emerald-400" />
              <span>Public Ad Library: Longevity & Iteration Scraped</span>
            </div>
            <div className="flex items-center gap-2 bg-white/10 px-3 py-1.5 rounded-xl border border-white/10">
              <CheckCircle className="w-4 h-4 text-emerald-400" />
              <span>Gemini AI: 5-Signal Creative Quality Graded</span>
            </div>
            <div className="flex items-center gap-2 bg-white/10 px-3 py-1.5 rounded-xl border border-white/10">
              <Lock className="w-4 h-4 text-amber-400" />
              <span>Private Metrics: Plugs in via OAuth Token</span>
            </div>
          </div>
        </div>
      </div>

      {/* Category Tabs */}
      <div className="flex flex-wrap gap-2 pb-2">
        {categories.map((cat) => (
          <button
            key={cat}
            onClick={() => setSelectedCategory(cat)}
            className={`px-4 py-2 rounded-2xl text-xs font-bold transition-all ${
              selectedCategory === cat
                ? 'bg-brand text-white shadow-md shadow-brand/20'
                : 'bg-white text-slate-600 border border-slate-200 hover:bg-slate-50'
            }`}
          >
            {cat}
          </button>
        ))}
      </div>

      {/* Metrics Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {filteredItems.map((metric) => (
          <div
            key={metric.id || metric.metric_name}
            className="bg-white p-6 rounded-2xl border border-slate-200/80 shadow-sm hover:border-brand-200 hover:shadow-card transition-all flex flex-col justify-between"
          >
            <div>
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center gap-2">
                  <div className="p-2 rounded-xl bg-slate-50 border border-slate-100">
                    {getCategoryIcon(metric.category)}
                  </div>
                  <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400">
                    {metric.category}
                  </span>
                </div>

                <span className="inline-flex items-center gap-1 text-[10px] font-bold text-amber-700 bg-amber-50 px-2 py-0.5 rounded-full border border-amber-200/60">
                  <Lock className="w-2.5 h-2.5" />
                  API Required
                </span>
              </div>

              <h4 className="text-base font-bold text-slate-900 mb-2">
                {metric.metric_name}
              </h4>

              <p className="text-xs text-slate-600 leading-relaxed">
                {metric.description}
              </p>
            </div>

            <div className="mt-5 pt-4 border-t border-slate-100 flex items-center justify-between text-[11px]">
              <span className="font-semibold text-slate-400">Status</span>
              <span className="font-bold text-brand-700 flex items-center gap-1">
                Tracked once connected to Meta Ads Manager API
              </span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
